# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- frontend

pool:
  vmImage: ubuntu-latest

variables:
  buildid: $(Build.BuildId)


stages:
  - stage:
    displayName: Building
    jobs:
    - job: 
      displayName: Installing Docker cli
      steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
          releaseType: stable
      - task: Docker@2
        inputs:
          containerRegistry: 'Dockerhub'
          repository: 'frontend'
          command: 'build'
          Dockerfile: '**/src/frontend/Dockerfile'
      - script: "sudo docker images"


      - task: trivy@1
        inputs:
          version: 'latest'
          path: 'frontend'