images:
  repository: shashidher
  tag: ''
serviceAccounts:
  create: true
  annotations: {}
  annotationsOnlyForCartservice: false
networkPolicies:
  create: false
sidecars:
  create: false
authorizationPolicies:
  create: false
opentelemetryCollector:
  create: false
  name: opentelemetrycollector
  projectId: PROJECT_ID
googleCloudOperations:
  profiler: false
  tracing: false
  metrics: false
seccompProfile:
  enable: false
  type: RuntimeDefault
adService:
  create: true
  name: adservice
  tag: 00
  resources:
    requests:
      cpu: 200m
      memory: 180Mi
    limits:
      cpu: 300m
      memory: 300Mi
cartService:
  create: true
  name: cartservice
  tag: 00
  resources:
    requests:
      cpu: 200m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 128Mi
checkoutService:
  create: true
  name: checkoutservice
  tag: 00
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
currencyService:
  create: true
  name: currencyservice
  tag: 00
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
emailService:
  create: true
  name: emailservice
  tag: 00
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
frontend:
  create: true
  name: frontend
  tag: 00
  externalService: true
  cymbalBranding: false
  platform: local
  singleSharedSession: false
  virtualService:
    create: false
    hosts:
      - '*'
    gateway:
      name: asm-ingressgateway
      namespace: asm-ingress
      labelKey: asm
      labelValue: ingressgateway
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
loadGenerator:
  tag: 00
  create: true
  name: loadgenerator
  checkFrontendInitContainer: true
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
paymentService:
  create: true
  tag: 00
  name: paymentservice
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
productCatalogService:
  create: true
  tag: 00
  name: productcatalogservice
  extraLatency: ''
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
recommendationService:
  create: true
  tag: 00
  name: recommendationservice
  resources:
    requests:
      cpu: 100m
      memory: 220Mi
    limits:
      cpu: 200m
      memory: 450Mi
shippingService:
  create: true
  tag: 00
  name: shippingservice
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
cartDatabase:
  type: redis
  connectionString: redis-cart:6379
  inClusterRedis:
    create: true
    name: redis-cart
    publicRepository: true
  externalRedisTlsOrigination:
    enable: false
    name: exernal-redis-tls-origination
    endpointAddress: ''
    endpointPort: ''
    certificate: ''
shoppingAssistantService:
  create: false
  name: shoppingassistantservice
