on:
  repository_dispatch:
    types: 'do-something'
jobs:
  cartsetvice:
    name: updating cartservice
    runs-on: ubuntu-latest

    permissions: write-all
    steps:
      - name: Get Latest Tag
        run: |
          LATEST_TAG=$(curl -s https://hub.docker.com/v2/namespaces/shashidher/repositories/cartservice/tags | jq -r '.results | .[0].name') >> $GITHUB_ENV
          echo "cartService=$(curl -s https://hub.docker.com/v2/namespaces/shashidher/repositories/cartservice/tags | jq -r '.results | .[0].name')" >> $GITHUB_ENV
          echo "currencyservice=$(curl -s https://hub.docker.com/v2/namespaces/shashidher/repositories/currencyservice/tags | jq -r '.results | .[0].name')" >> $GITHUB_ENV
          echo "emailservice=$(curl -s https://hub.docker.com/v2/namespaces/shashidher/repositories/emailservice/tags | jq -r '.results | .[0].name')" >> $GITHUB_ENV
          echo "recommendationservice=$(curl -s https://hub.docker.com/v2/namespaces/shashidher/repositories/recommendationservice/tags | jq -r '.results | .[0].name')" >> $GITHUB_ENV
          echo "checkoutservice=$(curl -s https://hub.docker.com/v2/namespaces/shashidher/repositories/checkoutservice/tags | jq -r '.results | .[0].name')" >> $GITHUB_ENV
          echo "loadgenerator=$(curl -s https://hub.docker.com/v2/namespaces/shashidher/repositories/loadgenerator/tags | jq -r '.results | .[0].name')" >> $GITHUB_ENV
          echo "paymentservice=$(curl -s https://hub.docker.com/v2/namespaces/shashidher/repositories/paymentservice/tags | jq -r '.results | .[0].name')" >> $GITHUB_ENV
          echo "productcatalogservice=$(curl -s https://hub.docker.com/v2/namespaces/shashidher/repositories/productcatalogservice/tags | jq -r '.results | .[0].name')" >> $GITHUB_ENV
          echo "shippingservice=$(curl -s https://hub.docker.com/v2/namespaces/shashidher/repositories/shippingservice/tags | jq -r '.results | .[0].name')" >> $GITHUB_ENV
          echo "adservice=$(curl -s https://hub.docker.com/v2/namespaces/shashidher/repositories/adservice/tags | jq -r '.results | .[0].name')" >> $GITHUB_ENV
          echo "shoppingassistantservice=$(curl -s https://hub.docker.com/v2/namespaces/shashidher/repositories/shoppingassistantservice/tags | jq -r '.results | .[0].name')" >> $GITHUB_ENV
          echo "frontend=$(curl -s https://hub.docker.com/v2/namespaces/shashidher/repositories/frontend/tags | jq -r '.results | .[0].name')" >> $GITHUB_ENV
          # echo "Latest tag: $LATEST_TAG"
          # Set LATEST_TAG as an environment variable
          # echo "LATEST_TAG=$LATEST_TAG"
      

      - uses: actions/checkout@v4
      - name: checking file
        run: ls
      - uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helm-chart/values.yaml'
          branch: main
          targetBranch: main
          createPR: 'true'
          description: Test GitHub Action
          message: 'Update All Images' 
          title: 'Version Updates '
          changes: |
            {
             "cartService.tag": "${{ env.cartService }}",
             "currencyService.tag": "${{ env.currencyservice }}",
             "emailService.tag": "${{ env.emailservice }}",
             "recommendationService.tag": "${{ env.recommendationservice }}",
             "checkoutService.tag": "${{ env.checkoutservice }}",
             "loadGenerator.tag": "${{ env.loadgenerator }}",
             "paymentService.tag": "${{ env.paymentservice }}",
             "productCatalogService.tag": "${{ env.productcatalogservice }}",
             "shippingService.tag": "${{ env.shippingservice }}",
             "adService.tag": "${{ env.adservice }}",
             "shoppingAssistantService.tag": "${{ env.shoppingassistantservice }}",
             "frontend": "${{ env.frontend }}"
            }
