on:
  repository_dispatch:
    types: 'do-something'
jobs:
  cartsetvice:
    name: updating cartservice
    runs-on: ubuntu-latest

    permissions: write-all
    steps:
      - name: Get Latest Tag
        run: |
          LATEST_TAG=$(curl -s https://hub.docker.com/v2/namespaces/shashidher/repositories/cartservice/tags | jq -r '.results | .[0].name')
          echo "Latest tag: $LATEST_TAG"
          # Add the line below to set the pipeline variable
          echo "::set-output name=LATEST_TAG::$LATEST_TAG"


      - uses: actions/checkout@v4
      - uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helm-chart/values.yaml'
          branch: main
          targetBranch: main
          createPR: 'true'
          description: Test GitHub Action
          message: 'Update All Images' 
          title: 'Version Updates '
          changes: |
            {
              "cartService.tag": "${{ steps.Get-Latest-Tag.outputs.LATEST_TAG }}",
            }